name: CI

on:
  push:
  schedule:
    - cron: '0 10 */7 * *'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Composer install
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest

      - name: PHPUnit
        run: vendor/bin/phpunit --testdox --colors=always
